import blueSkies from "@/assets/candle-blue-skies.jpg";
import rosePearl from "@/assets/candle-rose-pearl.jpg";
import vanillaBlush from "@/assets/candle-vanilla-blush.jpg";
import sunflower from "@/assets/candle-sunflower.jpg";
import floralUrli from "@/assets/candle-floral-urli.jpg";
import coffeeLatte from "@/assets/candle-coffee-latte.jpg";
import roseQuartz from "@/assets/candle-rose-quartz.jpg";
import teddyBliss from "@/assets/candle-teddy-bliss.jpg";
import pastelHearts from "@/assets/candle-pastel-hearts.jpg";
import evilEye from "@/assets/candle-evil-eye.jpg";
import modakCandle from "@/assets/candle-modak.jpg";
import ladooCandle from "@/assets/candle-ladoo.jpg";
import katliCandle from "@/assets/candle-katli.jpg";
import jewel1 from "@/assets/p-jewel-1.jpg";
import jewel2 from "@/assets/p-jewel-2.jpg";
import jewel3 from "@/assets/p-jewel-3.jpg";
import jewel4 from "@/assets/p-jewel-4.jpg";
import jewel5 from "@/assets/p-jewel-5.jpg";
import jewel6 from "@/assets/p-jewel-6.jpg";
import jewel7 from "@/assets/p-jewel-7.jpg";
import jewel8 from "@/assets/p-jewel-8.jpg";
import jewel9 from "@/assets/p-jewel-9.jpg";
import jewel10 from "@/assets/p-jewel-10.jpg";
import jewel11 from "@/assets/p-jewel-11.jpg";
import jewel12 from "@/assets/p-jewel-12.jpg";

export type Product = {
  id: string;
  slug: string;
  name: string;
  tagline: string;
  price: number;
  compareAt?: number;
  image: string;
  gallery: string[];
  category: "candles" | "jewellery";
  subCategory: string;
  rating: number;
  reviews: number;
  stock: number;
  badge?: string;
  variants?: { label: string; options: string[] };
  description: string;
};

export const products: Product[] = [
  {
    id: "c1",
    slug: "blue-skies-candle",
    name: "Blue Skies Candle",
    tagline: "Coconut & Soy Wax",
    price: 1490,
    image: blueSkies,
    gallery: [blueSkies],
    category: "candles",
    subCategory: "Soy Candles",
    rating: 4.8,
    reviews: 142,
    stock: 25,
    badge: "Bestseller",
    description: "Hand-poured soy and coconut wax candle in a sky blue hue, adorned with hand-sculpted white wax clouds. Emits a clean, fresh ozone breeze.",
  },
  {
    id: "c2",
    slug: "rose-pearl-urli-candle",
    name: "Rose Pearl Urli Candle",
    tagline: "Dried Rose & Pearls",
    price: 1890,
    image: rosePearl,
    gallery: [rosePearl],
    category: "candles",
    subCategory: "Luxury Candles",
    rating: 4.9,
    reviews: 204,
    stock: 12,
    badge: "New",
    description: "An elegant floral-edged urli vessel filled with premium soy wax, decorated with rich crimson dried rose petals and fine simulated pearls.",
  },
  {
    id: "c3",
    slug: "vanilla-blush-candle",
    name: "Vanilla Blush Candle",
    tagline: "Two-Layer Heart Candle",
    price: 1290,
    image: vanillaBlush,
    gallery: [vanillaBlush],
    category: "candles",
    subCategory: "Handmade Candles",
    rating: 4.7,
    reviews: 98,
    stock: 15,
    description: "A dual-texture delight. The base features miniature red wax hearts suspended in a translucent gel wax, topped with a creamy layer of vanilla-scented soy wax.",
  },
  {
    id: "c4",
    slug: "sunflower-candle",
    name: "Sunflower Candle",
    tagline: "Warm Honey & Amber",
    price: 1590,
    image: sunflower,
    gallery: [sunflower],
    category: "candles",
    subCategory: "Jar Candles",
    rating: 4.9,
    reviews: 167,
    stock: 30,
    badge: "Trending",
    description: "A warm and inviting candle topped with a highly detailed, hand-molded yellow sunflower wax flower. Notes of sweet honey and golden amber.",
  },
  {
    id: "c5",
    slug: "floral-urli-candle",
    name: "Floral Urli Candle",
    tagline: "Sunflowers & Daisies",
    price: 1990,
    image: floralUrli,
    gallery: [floralUrli],
    category: "candles",
    subCategory: "Luxury Candles",
    rating: 5.0,
    reviews: 82,
    stock: 8,
    description: "A premium floral collection presented in metallic brass-toned molds, adorned with exquisite yellow sunflowers and white daisy wax flowers.",
  },
  {
    id: "c6",
    slug: "iced-latte-candle",
    name: "Iced Latte Candle",
    tagline: "Coffee & Cream Scented",
    price: 1390,
    image: coffeeLatte,
    gallery: [coffeeLatte],
    category: "candles",
    subCategory: "Jar Candles",
    rating: 4.9,
    reviews: 118,
    stock: 14,
    badge: "New",
    description: "A realistic iced coffee candle featuring layered creamy coffee wax, topped with realistic wax ice cubes and rich coffee scent.",
  },
  {
    id: "c7",
    slug: "rose-quartz-heart-candle",
    name: "Rose Quartz Heart Candle",
    tagline: "Rose Petals & Crystals",
    price: 1190,
    image: roseQuartz,
    gallery: [roseQuartz],
    category: "candles",
    subCategory: "Aromatherapy Candles",
    rating: 4.8,
    reviews: 74,
    stock: 22,
    description: "Adorable heart-shaped pink soy candles topped with real dried red rose petals and raw rose quartz crystal chips for positive energy.",
  },
  {
    id: "c8",
    slug: "teddy-bliss-heart-candle",
    name: "Teddy Bliss Heart Candle",
    tagline: "Pink Wax & Cute Bear",
    price: 990,
    image: teddyBliss,
    gallery: [teddyBliss],
    category: "candles",
    subCategory: "Decorative Candles",
    rating: 4.9,
    reviews: 85,
    stock: 18,
    badge: "Trending",
    description: "Delightful heart-shaped pink candles, each topped with a detailed, sleeping white wax teddy bear. Extremely cute and perfect for gifting.",
  },
  {
    id: "c9",
    slug: "pastel-hearts-collection",
    name: "Pastel Hearts Collection",
    tagline: "Assorted Pastel Hearts",
    price: 790,
    image: pastelHearts,
    gallery: [pastelHearts],
    category: "candles",
    subCategory: "Handmade Candles",
    rating: 4.7,
    reviews: 54,
    stock: 35,
    description: "A vibrant collection of assorted pastel-colored heart tealight candles in shades of pink, yellow, green, and lavender. Unscented.",
  },
  {
    id: "c10",
    slug: "evil-eye-protection-candle",
    name: "Evil Eye Protection Candle",
    tagline: "Dried Florals & Evil Eye",
    price: 1290,
    image: evilEye,
    gallery: [evilEye],
    category: "candles",
    subCategory: "Aromatherapy Candles",
    rating: 5.0,
    reviews: 93,
    stock: 10,
    description: "Beautiful heart-shaped white candles featuring real dried blue flower petals, crystal glitter, and an evil eye protection glass bead.",
  },
  {
    id: "c11",
    slug: "modak-scented-candles",
    name: "Modak Scented Candles",
    tagline: "Kesar Peda & Cardamom Scent",
    price: 690,
    image: modakCandle,
    gallery: [modakCandle],
    category: "candles",
    subCategory: "Festival Candles",
    rating: 4.9,
    reviews: 58,
    stock: 25,
    badge: "Festive Special",
    description: "A set of five exquisitely hand-sculpted orange Modak candles presented on a glass plate, garnished with real gold leaf flakes. Warm kesar and cardamom aroma.",
  },
  {
    id: "c12",
    slug: "motichoor-ladoo-candles",
    name: "Motichoor Ladoo Candles",
    tagline: "Sweet Boondi & Pistachio",
    price: 890,
    image: ladooCandle,
    gallery: [ladooCandle],
    category: "candles",
    subCategory: "Festival Candles",
    rating: 5.0,
    reviews: 74,
    stock: 15,
    badge: "Bestseller",
    description: "An authentic platter of highly detailed, hand-crafted orange Motichoor Ladoo candles, accented with delicate gold leaf. Releases warm, sweet boondi fragrance.",
  },
  {
    id: "c13",
    slug: "kaju-katli-candles",
    name: "Kaju Katli Fudge Candles",
    tagline: "Almond & Rose Scented",
    price: 790,
    image: katliCandle,
    gallery: [katliCandle],
    category: "candles",
    subCategory: "Festival Candles",
    rating: 4.8,
    reviews: 42,
    stock: 20,
    description: "Delightful diamond-cut off-white Kaju Katli candles on a glass plate, finished with real edible-grade silver leaf work. Releases a warm almond and rose fragrance.",
  },
  {
    id: "j1",
    slug: "petite-pearl-necklace",
    name: "Petite Pearl Necklace",
    tagline: "18k Gold-Plated",
    price: 2490,
    compareAt: 3290,
    image: jewel1,
    gallery: [jewel1, jewel2, jewel3],
    category: "jewellery",
    subCategory: "Necklaces",
    rating: 4.9,
    reviews: 421,
    stock: 14,
    badge: "Trending",
    variants: { label: "Length", options: ['16"', '18"', '20"'] },
    description: "A delicate gold-plated chain with a single pearl. Made for everyday.",
  },
  {
    id: "j2",
    slug: "pearl-drop-earrings",
    name: "Pearl Drop Earrings",
    tagline: "Freshwater Pearl",
    price: 1690,
    image: jewel2,
    gallery: [jewel2, jewel1, jewel4],
    category: "jewellery",
    subCategory: "Earrings",
    rating: 4.8,
    reviews: 198,
    stock: 21,
    description: "Hand-set freshwater pearls on hypoallergenic gold-plated hooks.",
  },
  {
    id: "j3",
    slug: "stacked-eternity-rings",
    name: "Eternity Stack Rings",
    tagline: "Pavé Crystal Trio",
    price: 3290,
    image: jewel3,
    gallery: [jewel3, jewel4, jewel1],
    category: "jewellery",
    subCategory: "Rings",
    rating: 5.0,
    reviews: 87,
    stock: 6,
    badge: "Limited",
    variants: { label: "Size", options: ["S", "M", "L"] },
    description: "Three slim bands, pavé set in shimmering crystals. Wear them stacked or solo.",
  },
  {
    id: "j4",
    slug: "rose-quartz-bracelet",
    name: "Rosé Bracelet",
    tagline: "Rose Gold Chain",
    price: 1890,
    image: jewel4,
    gallery: [jewel4, jewel1, jewel2],
    category: "jewellery",
    subCategory: "Bracelets",
    rating: 4.7,
    reviews: 134,
    stock: 27,
    description: "An adjustable rose gold chain with a hand-set crystal centerpiece.",
  },
  {
    id: "j5",
    slug: "marbled-enamel-bangle",
    name: "Marbled Enamel Bangle",
    tagline: "Pink & Cream Enamel Duo",
    price: 290,
    image: jewel5,
    gallery: [jewel5],
    category: "jewellery",
    subCategory: "Bracelets",
    rating: 4.8,
    reviews: 62,
    stock: 15,
    description: "An enamel-finished thick cuff bangle featuring marbled pink resin and silver metal bands. Includes a complementary cream-silver bangle.",
  },
  {
    id: "j6",
    slug: "wave-pearl-bracelet",
    name: "Wave Pearl Bracelet",
    tagline: "Gold-Plated Freshwater Pearls",
    price: 290,
    image: jewel6,
    gallery: [jewel6],
    category: "jewellery",
    subCategory: "Bracelets",
    rating: 4.9,
    reviews: 84,
    stock: 20,
    description: "A wave-like fluid gold chain set with tiny, premium simulated freshwater pearls. Features an adjustable lobster clasp.",
  },
  {
    id: "j7",
    slug: "heart-link-chain-bracelet",
    name: "Heart Link Chain Bracelet",
    tagline: "18k Gold-Plated Hearts",
    price: 290,
    image: jewel7,
    gallery: [jewel7],
    category: "jewellery",
    subCategory: "Bracelets",
    rating: 4.7,
    reviews: 49,
    stock: 32,
    description: "A continuous delicate gold chain composed of contiguous gold-plated hearts. Fits comfortably on any wrist size.",
  },
  {
    id: "j8",
    slug: "clover-gold-cuff",
    name: "Clover Gold Cuff",
    tagline: "Mother of Pearl Clover",
    price: 290,
    image: jewel8,
    gallery: [jewel8],
    category: "jewellery",
    subCategory: "Bracelets",
    rating: 5.0,
    reviews: 73,
    stock: 12,
    badge: "Bestseller",
    description: "A luxury-inspired gold bangle featuring a beautiful mother-of-pearl four-leaf clover centerpiece flanked by two diamond-like crystals.",
  },
  {
    id: "j9",
    slug: "marquise-blue-vine-bracelet",
    name: "Marquise Blue Vine Bracelet",
    tagline: "Blue Marquise Zirconia",
    price: 290,
    image: jewel9,
    gallery: [jewel9],
    category: "jewellery",
    subCategory: "Bracelets",
    rating: 4.9,
    reviews: 91,
    stock: 8,
    badge: "Trending",
    description: "An exquisite gold vine bracelet set with brilliant blue marquise-cut zirconia stones. Designed to represent flowing nature.",
  },
  {
    id: "j10",
    slug: "butterfly-filigree-cuff",
    name: "Butterfly Filigree Cuff",
    tagline: "Gold & Silver Dual Tone",
    price: 1890,
    image: jewel10,
    gallery: [jewel10],
    category: "jewellery",
    subCategory: "Bracelets",
    rating: 4.9,
    reviews: 58,
    stock: 14,
    badge: "Trending",
    description: "An exquisite open cuff bangle featuring highly detailed filigree butterflies in contrasting 18k gold-plated and sterling silver finishes.",
  },
  {
    id: "j11",
    slug: "hammered-silver-cuff",
    name: "Hammered Wave Silver Cuff",
    tagline: "Hand-Hammered Sterling Silver",
    price: 1490,
    image: jewel11,
    gallery: [jewel11],
    category: "jewellery",
    subCategory: "Bracelets",
    rating: 4.7,
    reviews: 32,
    stock: 20,
    description: "A wide, solid sterling silver cuff bangle showcasing a hand-hammered organic texture with fluid, wavy edges for a contemporary look.",
  },
  {
    id: "j12",
    slug: "gold-leaf-bypass-cuff",
    name: "Gold Leaf Bypass Cuff",
    tagline: "18k Gold-Plated Botanical",
    price: 1690,
    image: jewel12,
    gallery: [jewel12],
    category: "jewellery",
    subCategory: "Bracelets",
    rating: 5.0,
    reviews: 67,
    stock: 8,
    badge: "Limited",
    description: "A beautiful botanical bypass cuff bangle featuring highly detailed, hand-carved leaves in a brilliant 18k gold-plated finish.",
  },
];

export const candleCategories = [
  "Scented Candles",
  "Soy Candles",
  "Luxury Candles",
  "Jar Candles",
  "Decorative Candles",
  "Festival Candles",
  "Aromatherapy Candles",
  "Handmade Candles",
];

export const jewelleryCategories = [
  "Rings",
  "Necklaces",
  "Earrings",
  "Bracelets",
  "Anklets",
  "Silver Jewellery",
  "Gold Plated Jewellery",
  "Fashion Jewellery",
  "Bridal Jewellery",
];

export const getProduct = (slug: string) => products.find((p) => p.slug === slug);
export const formatINR = (n: number) =>
  new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(n);
